In [172]:
import sys
sys.path.insert(0, '/home/jindal/notebooks/jindal/NER/')
import os
import numpy as np 
from keras.utils import to_categorical
from validation import compute_f1
from keras.models import Model
from keras.layers import TimeDistributed,Conv1D,Dense,Embedding,Input,Dropout,LSTM,Bidirectional,MaxPooling1D,Flatten,concatenate
from prepro import readfile,createBatches,createMatrices,iterate_minibatches,addCharInformatioin,padding
from keras.utils import plot_model,Progbar
from keras.preprocessing.sequence import pad_sequences
from keras.initializers import RandomUniform
from keras.optimizers import Adam
import keras.backend as K
from sklearn.metrics import f1_score
from keras.callbacks import ModelCheckpoint
from numpy import newaxis
import sklearn
import subprocess
import fastText

In [38]:
def getCasing(word, caseLookup):   
    casing = 'other'
    
    numDigits = 0
    for char in word:
        if char.isdigit():
            numDigits += 1
            
    digitFraction = numDigits / float(len(word))
    
    if word.isdigit(): #Is a digit
        casing = 'numeric'
    elif digitFraction > 0.5:
        casing = 'mainly_numeric'
    elif word.islower(): #All lower case
        casing = 'allLower'
    elif word.isupper(): #All upper case
        casing = 'allUpper'
    elif word[0].isupper(): #is a title, initial char upper, then all lower
        casing = 'initialUpper'
    elif numDigits > 0:
        casing = 'contains_digit'
    
   
    return caseLookup[casing]


def createMatrices(sentences, label2Idx, case2Idx,char2Idx):
    #{'numeric': 0, 'allLower': 1, 'contains_digit': 6, 'PADDING_TOKEN': 7, 'other': 4, 'allUpper': 2, 'mainly_numeric': 5, 'initialUpper': 3}

        
    dataset = []
    
    wordCount = 0
    unknownWordCount = 0
    
    for sentence in sentences:
        wordIndices = []
        caseIndices = []
        charIndices = []
        labelIndices = []
        
        for word,char,label in sentence:  
            charIdx = []
            for x in char:
                if x in char2Idx.keys():
                    charIdx.append(char2Idx[x])
                else:
                    charIdx.append(char2Idx['UNKNOWN'])
            #Get the label and map to int            
            wordIndices.append(word)
            caseIndices.append(getCasing(word, case2Idx))
            charIndices.append(charIdx)
            labelIndices.append(label2Idx[label])
           
        dataset.append([wordIndices, caseIndices, charIndices, labelIndices]) 
        
    return dataset

def padding(Sentences):
    maxlen = 52
    for sentence in Sentences:
        char = sentence[2]
        for x in char:
            maxlen = max(maxlen,len(x))
    for i,sentence in enumerate(Sentences):
        Sentences[i][2] = pad_sequences(Sentences[i][2],52,padding='post')
    return Sentences



In [39]:
epochs = 80
trainable = True

In [40]:
from keras_contrib.layers import CRF


In [41]:
def tag_dataset(dataset):
    correctLabels = []
    predLabels = []
    b = Progbar(len(dataset))
    for i,data in enumerate(dataset):    
        tokens, casing,char, labels = data
        tokens = np.asarray([tokens])     
        casing = np.asarray([casing])
        char = np.asarray([char])
        pred = model.predict([tokens, casing,char], verbose=False)[0]   
        pred = pred.argmax(axis=-1) #Predict the classes            
        correctLabels.append(labels)
        predLabels.append(pred)
        b.update(i)
    return predLabels, correctLabels

In [ ]:
# changing all deriv and part to misc. with BIO
def modify_labels(dataset):
    bad_labels = ['I-PERderiv','I-OTHpart','B-ORGderiv', 'I-OTH','B-OTHpart','B-LOCderiv','I-LOCderiv','I-OTHderiv','B-PERderiv','B-OTHderiv','B-PERpart','I-PERpart','I-LOCpart','B-LOCpart','I-ORGpart','I-ORGderiv','B-ORGpart','B-OTH']
    for sentence in dataset:
        for word in sentence:
            label = word[1]
            if label in bad_labels:
                first_char = label[0]
                if first_char == 'B' :
                    word[1] = 'B-MISC'
                else:
                    word[1] = 'I-MISC'
    return dataset
                

In [42]:

# preproecessing data from GermEval
def get_sentences(path):
    sentences=[]
    with open(path,'rb') as f:
    #     lines = f.readlines()
        sentence=[]
        for line in f:
            try:
                splits = [x.decode() for x in line.split()]
            except Exception as e:
                continue
            try:
                if splits[0]!='#':
                    temp = [splits[1],splits[2]]
                    sentence.append(temp)
                else:
                    if len(sentence):
                        sentences.append(sentence)
                    sentence=[]
            except Exception as e:
                continue
    return sentences



In [ ]:

# preproecessing data from Conll
def get_sentences(filename):
    '''
        -DOCSTART- -X- -X- O

    EU NNP B-NP B-ORG
    rejects VBZ B-VP O
    German JJ B-NP B-MISC
    call NN I-NP O
    to TO B-VP O
    boycott VB I-VP O
    British JJ B-NP B-MISC
    lamb NN I-NP O
    . . O O
    
    '''
    
    '''
    read file
    return format :
    [ ['EU', 'B-ORG'], ['rejects', 'O'], ['German', 'B-MISC'], ['call', 'O'], ['to', 'O'], ['boycott', 'O'], ['British', 'B-MISC'], ['lamb', 'O'], ['.', 'O'] ]
    '''
    f = open(filename,'rb')
    sentences = []
    sentence = []
    for line in f:
        splits = line.split()
        try:
            word=splits[0].decode()
            if word=='-DOCSTART-':
                continue
            label=splits[-1].decode()
            temp=[word,label]
            sentence.append(temp)
        except Exception as e:
            if len(sentence)!=0:
                sentences.append(sentence)
                sentence=[]
    return sentences



In [43]:
trainSentences = get_sentences('/home/jindal/notebooks/Resources/GermEVAL/NER-de-train.tsv')
devSentences = get_sentences('/home/jindal/notebooks/Resources/GermEVAL/NER-de-dev.tsv')
testSentences = get_sentences('/home/jindal/notebooks/Resources/GermEVAL/NER-de-test.tsv')

print(len(trainSentences))
print(len(devSentences))
print(len(testSentences))


23999
2199
5099


In [ ]:
# conll
train_sentences = get_sentences('/home/jindal/notebooks/Resources/CONLL/deu/deu_utf.train')
dev_sentences = get_sentences('/home/jindal/notebooks/Resources/CONLL/deu/deu_utf.testa')
test_sentences = get_sentences('/home/jindal/notebooks/Resources/CONLL/deu/deu_utf.testb')

print(len(train_sentences))
print(len(dev_sentences))
print(len(test_sentences))


In [44]:
print(trainSentences[100])

[['Der', 'O'], ['Meteoritensucher', 'O'], ['hatte', 'O'], ['im', 'O'], ['Frühjahr', 'O'], ['auf', 'O'], ['der', 'O'], ['dänischen', 'B-LOCderiv'], ['Insel', 'O'], ['Lolland', 'B-LOC'], ['30', 'O'], ['Gramm', 'O'], ['eines', 'O'], ['Meteoriten', 'O'], ['aufgespürt', 'O'], [',', 'O'], ['der', 'O'], ['Mitte', 'O'], ['Januar', 'O'], ['über', 'O'], ['Nordeuropa', 'B-LOC'], ['beobachtet', 'O'], ['worden', 'O'], ['war', 'O'], ['.', 'O']]


In [45]:
labelSet = set()
characters= set()

for dataset in [trainSentences, devSentences, testSentences]:
    for sentence in dataset:
        for word, label in sentence:
            for char in word:
                characters.add(char)
            labelSet.add(label)

In [46]:
print(len(labelSet))

25


In [47]:
# :: Create a mapping for the labels ::
label2Idx = {}
for label in labelSet:
    label2Idx[label] = len(label2Idx)

In [48]:
print(label2Idx)

{'I-LOCderiv': 0, 'B-LOC': 1, 'B-PERpart': 14, 'I-LOCpart': 4, 'B-OTH': 15, 'I-ORGderiv': 17, 'B-ORGderiv': 5, 'B-LOCpart': 19, 'O': 6, 'I-LOC': 7, 'I-PERderiv': 16, 'B-OTHderiv': 2, 'I-OTHderiv': 8, 'I-ORGpart': 21, 'I-PER': 3, 'B-PER': 22, 'B-OTHpart': 11, 'B-PERderiv': 9, 'I-PERpart': 24, 'B-ORG': 10, 'B-LOCderiv': 23, 'I-OTH': 18, 'I-ORG': 12, 'B-ORGpart': 13, 'I-OTHpart': 20}


In [13]:
# :: Hard coded case lookup ::
case2Idx = {'numeric': 0, 'allLower':1, 'allUpper':2, 'initialUpper':3, 'other':4, 'mainly_numeric':5, 'contains_digit': 6, 'PADDING_TOKEN':7}
caseEmbeddings = np.identity(len(case2Idx), dtype='float32')

In [14]:
print(caseEmbeddings)
print(case2Idx)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
{'other': 4, 'allLower': 1, 'numeric': 0, 'mainly_numeric': 5, 'contains_digit': 6, 'PADDING_TOKEN': 7, 'allUpper': 2, 'initialUpper': 3}


In [15]:
print(type(trainSentences))

<class 'list'>


In [49]:
print(trainSentences[0])

[['Schartau', 'B-PER'], ['sagte', 'O'], ['dem', 'O'], ['"', 'O'], ['Tagesspiegel', 'B-ORG'], ['"', 'O'], ['vom', 'O'], ['Freitag', 'O'], [',', 'O'], ['Fischer', 'B-PER'], ['sei', 'O'], ['"', 'O'], ['in', 'O'], ['einer', 'O'], ['Weise', 'O'], ['aufgetreten', 'O'], [',', 'O'], ['die', 'O'], ['alles', 'O'], ['andere', 'O'], ['als', 'O'], ['überzeugend', 'O'], ['war', 'O'], ['"', 'O'], ['.', 'O']]


In [50]:
char2Idx={}
for char in characters:
    char2Idx[char] = len(char2Idx)
char2Idx['UNKNOWN'] = len(char2Idx)
print(char2Idx)

{'Ö': 138, 'к': 1, 'Ş': 2, 'Á': 176, '⊃': 3, 'č': 4, '€': 232, '\x9a': 5, 'Ł': 6, ')': 7, '▪': 8, '°': 9, '·': 56, 'UNKNOWN': 328, '太': 13, 'Ž': 12, '傳': 188, '2': 180, 'Z': 242, '妃': 252, '§': 11, 'ā': 14, 'ó': 15, '~': 297, '동': 17, 'ź': 82, 'İ': 18, 'I': 19, 'т': 25, '.': 21, '“': 23, 'ế': 0, 'Π': 31, '別': 61, 'Т': 33, '@': 27, 'ǒ': 281, 'л': 30, 'ę': 32, '*': 275, 'p': 291, 'Â': 42, '_': 38, 'н': 36, 'ь': 37, 'ú': 308, 'r': 39, 'R': 40, ',': 41, 's': 44, '柯': 45, '+': 46, 'Ä': 47, 'α': 48, 'è': 49, 'k': 223, 'È': 68, 'œ': 52, 'c': 53, 'г': 54, 'ъ': 57, '$': 58, ';': 59, 'e': 60, 'B': 62, 'A': 63, '\x95': 64, 'é': 66, 'o': 65, 'и': 67, '≤': 312, '\x80': 313, 'ʻ': 69, 'λ': 70, 'ņ': 71, 'y': 224, 'û': 73, 'æ': 75, '⋅': 76, 'ö': 77, '守': 79, '貴': 81, 'κ': 55, '—': 83, '李': 84, '©': 86, 'ã': 131, 'Å': 87, 'ρ': 88, '−': 89, '<': 90, '×': 243, 'б': 91, 'η': 239, 'ς': 93, 'р': 94, 'h': 95, 'Q': 96, 'î': 97, '’': 10, 'τ': 99, 'x': 133, 'ж': 100, '\x96': 101, 'о': 102, 'с': 270, 'ō': 105, 'š

In [18]:
print(trainSentences[0]) 

[['Schartau', 'B-PER'], ['sagte', 'O'], ['dem', 'O'], ['"', 'O'], ['Tagesspiegel', 'B-ORG'], ['"', 'O'], ['vom', 'O'], ['Freitag', 'O'], [',', 'O'], ['Fischer', 'B-PER'], ['sei', 'O'], ['"', 'O'], ['in', 'O'], ['einer', 'O'], ['Weise', 'O'], ['aufgetreten', 'O'], [',', 'O'], ['die', 'O'], ['alles', 'O'], ['andere', 'O'], ['als', 'O'], ['überzeugend', 'O'], ['war', 'O'], ['"', 'O'], ['.', 'O']]


In [51]:
ft = fastText.load_model("/home/jindal/notebooks/fastText/wiki.de.bin")

nb_embedding_dims = ft.get_dimension()

In [54]:
print(len(trainSentences[0]))

25


In [55]:
print(trainSentences[0])

[['Schartau', 'B-PER'], ['sagte', 'O'], ['dem', 'O'], ['"', 'O'], ['Tagesspiegel', 'B-ORG'], ['"', 'O'], ['vom', 'O'], ['Freitag', 'O'], [',', 'O'], ['Fischer', 'B-PER'], ['sei', 'O'], ['"', 'O'], ['in', 'O'], ['einer', 'O'], ['Weise', 'O'], ['aufgetreten', 'O'], [',', 'O'], ['die', 'O'], ['alles', 'O'], ['andere', 'O'], ['als', 'O'], ['überzeugend', 'O'], ['war', 'O'], ['"', 'O'], ['.', 'O']]


In [66]:
def createBatches(dataset):
    l = []
    for i in dataset:
        l.append(len(i))
    l = set(l)
    print(len(l))
    batches = []
    batch_len = []
    z = 0
    for i in l:
        temp = []
        for batch in dataset:
            if len(batch) == i:
                temp.append(batch)
                z += 1
        batches.append(temp)
#         batch_len.append(z)
    return batches

In [82]:
train_batches = createBatches(trainSentences)
dev_batches = createBatches(devSentences)


51
45


In [72]:
print(batches[0][0])
print(batches[0][1])
print(len(batches))
print(len(batches[0]))
print(batches[1][0])

[['Alles', 'O'], ['richtig', 'O'], ['.', 'O']]
[['Farben', 'O'], ['eingeführt', 'O'], ['.', 'O']]
51
3
[['Brennt', 'O'], ['nichts', 'O'], ['nieder', 'O'], ['.', 'O']]


In [87]:
def generator(batches: 'list of training/dev sentences- batches already created'):
    global line_number
    
    while True:
        total_lines = len(dataset)
        for batch in batches:
            word_embeddings = []
            case_embeddings = []
            char_embeddings = []

            output_labels = []
            for index in range(len(batch)): # batches made according to the size of the sentences. len(batch) gives the size of current batch            
#                 index = line_number%total_lines
#                 line_number+=1
                sentence = batch[index]
    #             print(sentence)
                temp_casing = []
                temp_char=[]
                temp_word=[]
                temp_output=[]
                for word in sentence:
                    word, label = word
                    casing =getCasing(word, case2Idx)
                    temp_casing.append(casing)
                    temp_char2=[]
                    for char in word:
                        if char in char2Idx.keys():
                            temp_char2.append(char2Idx[char])
                        else:
                            temp_char2.append(char2Idx['UNKNOWN']) # To incorporate the words which are not in the vocab
                    temp_char2 = np.array(temp_char2)
                    temp_char.append(temp_char2)
                    word_vector = ft.get_word_vector(word.lower())
                    temp_word.append(word_vector)
                    temp_output.append(label2Idx[label])
                temp_char = pad_sequences(temp_char, 52)
                word_embeddings.append(temp_word)
                case_embeddings.append(temp_casing)
                char_embeddings.append(temp_char)
                temp_output = to_categorical(temp_output, 25)
                output_labels.append(temp_output)
    #             output_labels = to_categorical()
    #             output_labels = np.array(output_labels)
    #             output_labels = output_labels[...,newaxis]

    #             print(np.array(word_embeddings).shape)
    #             print(np.array(case_embeddings).shape)
    #             print(np.array(char_embeddings).shape)
    #             print(output_labels.shape)
    #             print("******************\n\n")
            yield ([np.array(word_embeddings), np.array(case_embeddings), np.array(char_embeddings)], np.array(output_labels))

In [78]:
line_number=0
for inp, out in train_generator(batches):
    word, case, char = inp
    print(word.shape)
    print(case.shape)
    print(char.shape)
    print(out.shape)
    print("********")

(3, 3, 300)
(3, 3)
(3, 3, 52)
(3, 3, 25)
********
(32, 4, 300)
(32, 4)
(32, 4, 52)
(32, 4, 25)
********
(127, 5, 300)
(127, 5)
(127, 5, 52)
(127, 5, 25)
********
(317, 6, 300)
(317, 6)
(317, 6, 52)
(317, 6, 25)
********
(497, 7, 300)
(497, 7)
(497, 7, 52)
(497, 7, 25)
********
(755, 8, 300)
(755, 8)
(755, 8, 52)
(755, 8, 25)
********
(913, 9, 300)
(913, 9)
(913, 9, 52)
(913, 9, 25)
********


KeyboardInterrupt: 

In [25]:
idx2Label = {v: k for k, v in label2Idx.items()}


In [79]:
%env CUDA_DEVICE_ORDER=PCI_BUS_ID
%env CUDA_VISIBLE_DEVICES=2

env: CUDA_DEVICE_ORDER=PCI_BUS_ID
env: CUDA_VISIBLE_DEVICES=2


In [175]:
words_input = Input(shape=(None,300),dtype='float32',name='words_input')
# words = Embedding(input_dim=wordEmbeddings.shape[0], output_dim=wordEmbeddings.shape[1],  weights=[wordEmbeddings], trainable=False)(words_input)
casing_input = Input(shape=(None,), dtype='int32', name='casing_input')
casing = Embedding(output_dim=caseEmbeddings.shape[1], input_dim=caseEmbeddings.shape[0], weights=[caseEmbeddings], trainable=False, name = 'case_embed')(casing_input)
character_input=Input(shape=(None,52,),name='char_input')
embed_char_out=TimeDistributed(Embedding(len(char2Idx),32,embeddings_initializer=RandomUniform(minval=-0.5, maxval=0.5)), name='char_embedding')(character_input)
# dropout= Dropout(0.5, name='dropout1')(embed_char_out)

# conv1d_out= TimeDistributed(Conv1D(kernel_size=3, filters=30, padding='same',activation='tanh', strides=1, name='conv'))(dropout)
# maxpool_out=TimeDistributed(MaxPooling1D(52), name='maxpool')(conv1d_out)
# char = TimeDistributed(Flatten())(maxpool_out)
# char = Dropout(0.5)(char)
# output = concatenate([words, casing, char])

kernel_sizes = (3, 4, 5)
conv_blocks = []
for sz in kernel_sizes[:1]:
    conv = TimeDistributed(Conv1D(
                         kernel_size=sz,
                         filters=32,
                         padding="same",
                         activation="relu",
                         strides=1))(embed_char_out)
    conv = TimeDistributed(MaxPooling1D(52))(conv)
    conv = TimeDistributed(Flatten())(conv)
#     conv = Dropout(0.5)(conv)
    conv_blocks.append(conv)
output = concatenate([words_input, casing, conv_blocks[0]])

output = Bidirectional(LSTM(200, return_sequences=True, dropout=0.50, recurrent_dropout=0.5))(output)
output = TimeDistributed(Dense(len(label2Idx)))(output)
crf = CRF(len(label2Idx))
output = crf(output)
model = Model(inputs=[words_input, casing_input,character_input], outputs=[output])
model.compile(loss=crf.loss_function, optimizer='nadam', metrics=[crf.accuracy])
# model.compile(loss='categorical_crossentropy', optimizer='nadam', )
model.summary()
# plot_model(model, to_file='model.png')

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
char_input (InputLayer)         (None, None, 52)     0                                            
__________________________________________________________________________________________________
char_embedding (TimeDistributed (None, None, 52, 32) 10528       char_input[0][0]                 
__________________________________________________________________________________________________
time_distributed_49 (TimeDistri (None, None, 52, 32) 3104        char_embedding[0][0]             
__________________________________________________________________________________________________
casing_input (InputLayer)       (None, None)         0                                            
__________________________________________________________________________________________________
time_distr

In [112]:
checkpoint = ModelCheckpoint('generator_NER_best.h5', monitor='f1_metric', verbose=1, save_best_only=True, period=1)


In [ ]:
# line_number=0
model.reset_states()
max_f1=0
for i in range(80):
    model.fit_generator(generator(train_batches), epochs=1, steps_per_epoch= len(batches))
    
    pred_labels=[]
    correct_labels=[]
    print(len(devSentences))
    
    if i>=50:
        for sentence in devSentences:
            temp_sentence=[]
            for word in sentence:
                w, correct_label = word
                correct_labels.append(label2Idx[correct_label])
                temp_sentence.append(w)
            pred_label = get_predictions(temp_sentence, model)
            pred_label = np.ndarray.tolist(pred_label[0])
        #     print(len(pred_label[0]))
            for label in pred_label:
                label = label.index(max(label))
                pred_labels.append(label)
        temp_f1 = f1_score(correct_labels, pred_labels, average='macro')
        if max_f1 < temp_f1:
            model.save('generator_NER_best.h5')
            max_f1 = temp_f1
    #     print((len(correct_labels), len(pred_labels)))
#     print(f1_score(correct_labels, pred_labels, average='macro'))
    
    
    

Epoch 1/1
51/51 [==============================] - 21s 412ms/step - loss: 0.5845 - acc: 0.8775
2199
Epoch 1/1
51/51 [==============================] - 18s 359ms/step - loss: 0.2917 - acc: 0.9278
2199
Epoch 1/1
51/51 [==============================] - 19s 363ms/step - loss: 0.2288 - acc: 0.9360
2199
Epoch 1/1
51/51 [==============================] - 19s 381ms/step - loss: 0.1976 - acc: 0.9415
2199
Epoch 1/1
51/51 [==============================] - 20s 390ms/step - loss: 0.2032 - acc: 0.9351
2199
Epoch 1/1
51/51 [==============================] - 19s 366ms/step - loss: 0.1531 - acc: 0.9486
2199
Epoch 1/1
51/51 [==============================] - 18s 358ms/step - loss: 0.1251 - acc: 0.9541
2199
Epoch 1/1
51/51 [==============================] - 18s 355ms/step - loss: 0.1104 - acc: 0.9529
2199
Epoch 1/1
51/51 [==============================] - 18s 356ms/step - loss: 0.1019 - acc: 0.9539
2199
Epoch 1/1
51/51 [==============================] - 19s 377ms/step - loss: 0.0881 - acc: 0.9565
2199


In [171]:
pred_labels=[]
correct_labels=[]
print(len(devSentences))
for sentence in devSentences:
    temp_sentence=[]
    for word in sentence:
        w, correct_label = word
        correct_labels.append(label2Idx[correct_label])
        temp_sentence.append(w)
    pred_label = get_predictions(temp_sentence, model)
    pred_label = np.ndarray.tolist(pred_label[0])
#     print(len(pred_label[0]))
    for label in pred_label:
        label = label.index(max(label))
        pred_labels.append(label)
print((len(pred_labels), len(correct_labels)))

2199
(41636, 41636)


In [136]:
for sentence in devSentences:
    for word in sentence:
        w, label = word
        print(w)

Gleich
darauf
entwirft
er
seine
Selbstdarstellung
"
Ecce
homo
"
in
enger
Auseinandersetzung
mit
diesem
Bild
Jesu
.
1980
kam
der
Crown
als
Versuch
von
Toyota
,
sich
in
der
Oberen
Mittelklasse
zu
etablieren
,
auch
nach
Deutschland
.
–
4:26
#
Sometime
Ago/La
Fiesta
–
23:18
Alle
Stücke
wurden
von
Corea
komponiert
mit
Ausnahme
der
einleitenden
Improvisation
zu
Sometime
Ago
.
Bis
2013
steigen
die
Mittel
aus
dem
EU-Budget
auf
rund
120
Millionen
Euro
.
Daraus
entwickelte
sich
im
Rokoko
die
Sitte
des
gemeinsamen
Weinens
im
Theater
,
das
die
Standesgrenzen
innerhalb
des
Publikums
überbrücken
sollte
.
Die
Spinne
hatte
sie
mit
Seidenfäden
an
ihrem
Schwanz
gefesselt
und
nach
oben
gezogen
.
In
Deutschland
ist
nach
StGB
eine
Anwerbung
für
die
Fremdenlegion
strafbar
.
Am
Donnerstag
wird
sich
zeigen
,
ob
die
Idee
der
DLR-Forscher
funktioniert
.
Der
sechste
Lauf
der
ADAC
GT
Mastersstand
ganz
klar
im
Mittelpunkt
des
Motorsport-Wochenendes
auf
dem
Eurospeedway
Lausitz
.
Nach
den
schwächeren
Vorgaben
der
W

Rolle
.
In
der
letzten
Phase
des
Krieges
wurde
die
Aichi
D3A
in
ihrer
angestammten
Rolle
von
moderneren
Maschinen
ersetzt
und
in
der
Folge
auch
zu
Kamikaze
-Einsätzen
verwendet
.
Öffnen
in
der
Binärbildmorphologie
Im
Fall
der
Binärbildmorphologie
ist
der
Verband
gegeben
durch
den
Potenzmengenverband
aller
Bildpunkte
.
Am
zweiten
Weihnachtsfeiertag
startet
das
SWR
Fernsehen
die
erste
Staffel
der
neuen
Sendereihe
„
oper
kompakt
“
.
Die
jeweils
aktuellen
Bauabschnitte
werden
auch
für
sie
gesperrt
.
PMID
17117481
Mit
den
Endogenen
Retroviren
wurden
aus
den
infektiösen
Viren
,
die
aus
Transposons
entstanden
,
wieder
Teile
der
Genome
.
Aber
auch
hier
blieb
ihm
die
Anerkennung
bis
nach
seinem
Tod
versagt
.
1968
kommt
er
nach
Europa
,
wo
er
u.a
.
auch
in
der
John
Peel's
Top
Gear
Show
auftritt
.
Madonna
hatte
zu
diesem
Zeitpunkt
einen
Scheidungskrieg
mit
Sean
Penn
hinter
sich
gebracht
(
der
Song
"
Till
Death
Do
Us
Part
"
handelt
davon
)
und
ihre
Familie
zeigte
sich
nicht
begeistert
von
ihrem
Le

fast
zerstört
.
Der
Boden
unter
jedem
Sitz
ist
vertieft
,
wodurch
es
möglich
ist
,
die
Wagen
um
90°
zu
drehen
mit
ausreichend
Platz
für
die
Füße
der
Fahrgäste
.
The
Lancet
Infectious
Diseases
,
Band
6,
2006
,
S.
234–241
,
Volksglaube
Auch
heutzutage
werden
Befallene
oft
noch
ungerechtfertigt
stigmatisiert
,
obwohl
die
Sauberkeit
bei
der
Übertragung
in
modernen
Industriestaaten
kaum
mehr
eine
dominante
Rolle
spielt
.
Denn
eine
solche
Einengung
auf
diesem
wichtigen
Verbindungsweg
zwischen
Mittweida
und
Ringethal/Falkenhain
sei
auf
Dauer
keine
Lösung
.
"
Insight
"
gibt
es
nicht
mehr
als
eigenständige
Sendung
.
2.
Michael
Jackson
:
Arzt
vor
Gericht
—
"
Ich
bin
ein
unschuldiger
Mann
"
Hauptgründe
dafür
waren
,
dass
die
Musiker
nicht
von
dem
Geld
leben
konnten
,
das
sie
mit
der
Band
verdienten
,
und
die
mangelnde
Unterstützung
durch
ihre
Plattenfirma
.
Der
Hauptbuchhalter
Friedrich
Peters
übernahm
die
Firma
seiner
bisherigen
Chefs
.
In
der
Neuzeit
war
das
kurze
Pallium
mit
schwarzen
Kreuzen


wird
daher
davon
ausgegangen
,
dass
bei
den
meisten
Fällen
erst
eine
Dauerexposition
zur
Infektion
führen
kann
und
keine
einmalige
Aufnahme
der
Bandwurmeier
.
Umgekehrt
führten
als
unehrenhaft
betrachtete
Verhaltensweisen
auch
zum
Verlust
der
Satisfaktionsfähigkeit
.
Die
kleine
Wachspuppe
habe
die
"
berühmten
Schmolllippen
ihrer
Mutter
und
feine
Gesichtszüge
"
.
Auflage
,
Franzis
Verlag
,
München
,
1970
*
Gustav
Büscher
,
A.
Wiegemann
:
Kleines
ABC
der
Elektroakustik
.
Andere
Regionen
machten
es
vor
und
mit
der
Initiative
aus
Spiegelau
,
über
die
Gästekarte
kostenlos
Igelbus
fahren
zu
können
,
geriet
der
Stein
auch
hier
ins
Rollen
.
Ein
deutscher
Tourist
,
der
sich
auf
einem
Boot
in
Sicherheit
bringen
will
,
ertrinkt
.
Die
Seeblockade
wurde
am
15.
August
718
aufgegeben
.
Es
ist
nur
dieser
Ring
,
der
in
gewissem
Sinn
die
Bezeichnung
„
Kalenderstein
“
rechtfertigt
.
1561
wurde
er
Mitglied
des
„
inneren
“
beziehungsweise
„
kleinen
Rats
“
,
also
des
15-köpfigen
Patrizierrats
,
der
aus
sein

gleiches
Recht
für
alle
gelten
,
sagte
er
am
Montag
.
Bei
der
symbolischen
Schlüsselübergabe
durch
Franz
Beckenbauer
hofft
Jones
auch
auf
den
ersten
Gedankenaustausch
mit
dem
«
Kaiser
»
.
Ausschlaggebend
für
die
Wirkung
des
Dreipunktgurtes
ist
der
Umstand
,
dass
dieser
den
Passagier
in
seinem
Sitz
fixiert
.
75
Prozent
der
Personen
,
die
bei
einem
Unfall
aus
dem
Fahrzeug
geschleudert
werden
,
überleben
nicht
(
2
)
.
AFP/SID/Miguel
Riopa
Grund
für
den
Rücktritt
von
Portugals
Liga-Präsident
:
Hulk
Der
Präsident
der
portugiesischen
Liga
(
LPFP
)
hat
seinen
Rücktritt
eingereicht
.
Es
ist
sicherlich
nicht
wahr
,
dass
Ludwig
Paris
nicht
mochte
.
Auseinandersetzungen
mit
den
beiden
Grafen
um
die
Kirchenzucht
sowie
die
Haltung
der
Grafen
im
sogen
.
Schmalkaldischen
Krieg
veranlassten
Forster
,
im
Jahr
1547
um
die
Entlassung
aus
seinem
Amt
nachzusuchen
.
Beide
Ruderschäfte
sind
ausgebrochen
.
"
Nach
dem
zweiten
Schreiben
geben
die
meisten
Vermieter
klein
bei
"
,
sagt
Christiane
Holländer
,
Recht

Johannitern
bestimmt
.
Deshalb
werde
ich
mich
von
sämtlichen
Anteilen
trennen
.
Ähnliche
Info-Post
sei
an
die
29
Verkaufsstellen
von
pyrotechnischen
Erzeugnissen
im
Stadtgebiet
verschickt
worden
.
Die
erarbeiteten
Lösungsvarianten
müssen
bewertet
werden
.
1910
wurde
er
Richter
am
dortigen
Nachlassgericht
;
diesen
Posten
bekleidete
er
bis
1939.
Politisch
war
Leahy
erstmals
zwischen
1911
und
1913
als
Abgeordneter
im
Repräsentantenhaus
von
Rhode
Island
tätig
.
Epoden
deshalb
,
weil
jeweils
ein
Langvers
mit
einem
refrainartigen
Kurzvers
abwechselt
.
"
Ich
bin
einer
der
letzten
Orchestermusiker
in
Deutschland
,
der
das
in
dieser
Kombination
macht
.
Auf
die
Frage
,
welche
politischen
Auswir­kungen
ein
neuer
Terroranschlag
in
den
USA
auf
Bushs
Parteikollegen
McCain
haben
würde
,
antwortete
er
-
wohl
et­was
zu
ehrlich
:
«
Es
wäre
ein
grosser
Vorteil
für
ihn
.
»
Der
Umsatz
verdoppelte
sich
auf
7,401
Mio
US-Dollar
(
5,845
Mio
Euro
)
.
Anfang
2008
notierte
die
Aktien
mit
über
55
Euro
pro
Aktie
,


aufgeführt
.
Dieser
Reichtum
findet
sich
auch
in
der
Architektur
jener
Epoche
wieder
,
in
der
die
berühmten
Barockkirchen
im
Stil
des
Barroco
Mineiro
errichtet
wurden
.
Das
Eine
und
Unveränderliche
ist
der
Erklärungsgrund
unserer
selbst
und
der
Welt
.
Die
Familie
umfasst
neben
einer
Reihe
von
ausgestorbenen
Arten
zwei
rezente
Arten
,
das
Eigentliche
Zweifingerfaultier
(
Choloepus
didactylus
)
und
das
Hoffmann-Zweifingerfaultier
(
Choloepus
hoffmanni
)
.
Um
die
Kosten
zu
senken
,
passte
man
die
Streckenführung
an
die
Topografie
an
,
was
zahlreiche
Kurven
zur
Folge
hatte
.
Als
erster
Hersteller
weltweit
wird
WD
dabei
2,5-Zoll-Festplatten
mit
750
Gigabyte
und
einem
Terabyte
anbieten
.
EU
erzwingt
offenes
Glasfasernetz
-
FTD
Das
superschnelle
Internet
der
neuen
Generation
soll
nach
dem
Willen
der
EU-Kommission
allen
interessierten
Anbietern
offenstehen
-
und
nicht
nur
den
großen
Telekomkonzernen
.
Dennoch
konnte
Muhammad
während
des
Italienisch-Osmanischen
Kriegs
mit
Unterstützung
Italien


Weltkrieges
jedoch
sofort
wieder
eingesetzt
.
Pinkwart
plädierte
im
Januar
dafür
,
die
Regelung
auszusetzen
,
Landesvater
Jürgen
Rüttgers
(
CDU
)
pflichtete
ihm
bei
.
Diese
geht
auf
eine
Initiative
des
Antifaschistischen
Arbeitskreises
des
Gustav-Heinemann-Bürgerhauses
in
Bremen-Vegesack
zurück
.
Nach
und
nach
gewann
er
allgemeine
öffentliche
Anerkennung
.
Presseberichten
zufolge
konnten
sich
Blatter
und
Beckenbauer
nicht
über
Redezeiten
einigen
,
weshalb
eine
Ansprache
allein
Köhler
überlassen
wurde
.
"
Microfluidic
Chip
Shop
"
heißt
die
Firma
,
die
der
Physiker
gegründet
hat
,
und
was
er
herstellt
,
sieht
aus
wie
ein
kleiner
Düsenflieger
aus
Plastik
,
der
von
winzigen
Kanälen
durchzogen
ist
.
10
Minuten
lesen
und
ich
schweife
mit
den
Gedanken
ab
.
So
weist
die
Northampton-Gruppe
starke
ionische
Einflüsse
auf
,
doch
ist
sie
wohl
–
möglicherweise
durch
Einwanderer
aus
Ionien
–
in
Italien
geschaffen
worden
.
1641
nahm
er
das
Amt
des
Stadtsyndicus
von
Stettin
an
.
1951
hatte
er
bereits
e

KeyboardInterrupt: 

In [ ]:
def get_predictions_validation

In [102]:
model.load_weights('generator_NER_best.h5')

In [150]:
def convert_sentence_to_input(sentence):
    word_embeddings = []
    case_embeddings = []
    char_embeddings = []

#     output_labels = []
    temp_casing = []
    temp_char=[]
    temp_word=[]
#     temp_output=[]
    for word in sentence:
        casing =getCasing(word, case2Idx)
        temp_casing.append(casing)
        temp_char2=[]
        for char in word:
            if char in char2Idx.keys():
                temp_char2.append(char2Idx[char])
            else:
                temp_char2.append(char2Idx['UNKNOWN']) # To incorporate the words which are not in the vocab
        temp_char2 = np.array(temp_char2)
        temp_char.append(temp_char2)
        word_vector = ft.get_word_vector(word.lower())
        temp_word.append(word_vector)
#         temp_output.append(label2Idx[label])
    temp_char = pad_sequences(temp_char, 52)
    word_embeddings.append(temp_word)
    case_embeddings.append(temp_casing)
    char_embeddings.append(temp_char)
#     temp_output = to_categorical(temp_output, 25)
#     output_labels.append(temp_output)
    ans = [np.array(word_embeddings), np.array(case_embeddings), np.array(char_embeddings)]
    return ans



In [152]:
def get_predictions(sentence, model):
    inp = convert_sentence_to_input(sentence)
    
    out = model.predict(inp)
    return out

In [151]:
for sentence in devSentences:
        for word in sentence:
            w, label = word
            temp_sentence = []
            temp_sentence.append(w)
        x = convert_sentence_to_input(temp_sentence)
#         print(pred_label)